backend:
  name: github
  repo: gyanvigyanbrhamgyan98-arch/my-secure-blog
  branch: main
  # नीचे यह लाइन जोड़ने से यह नेटलिफाई की जगह सीधे GitHub से ऑथेंटिकेट करेगा
  base_url: https://github.com
  auth_endpoint: login/oauth/authorize

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
